#!/usr/bin/env bash

set -euo pipefail

if ! [ -x "$(command -v flutter)" ] &>/dev/null; then
    echo "Please install flutter at version 3.10"
    exit 1
fi

dart format .
flutter test
flutter analyze
flutter gen-l10n

if ! [ -x "$(command -v pandoc)" ] &>/dev/null; then
    echo "Please install pandoc at version 3.1"
    exit 1
fi

pandoc \
    --columns=80 \
    --standalone \
    --from=gfm \
    --to=gfm \
    --output=README.md \
    README.md