// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0sRYbGZ9-yz6Nh00tf0NKFj_JKNAKvpM',
    appId: '1:970375826463:web:0707a9dacfac12c8a8d92a',
    messagingSenderId: '970375826463',
    projectId: 'micromentor-b8317',
    authDomain: 'micromentor-b8317.firebaseapp.com',
    storageBucket: 'micromentor-b8317.appspot.com',
    measurementId: 'G-9TXS7T646R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiqsogWVVldATr_p6737dANyyNCR0JaDc',
    appId: '1:970375826463:android:0a9f510b35ccade4a8d92a',
    messagingSenderId: '970375826463',
    projectId: 'micromentor-b8317',
    storageBucket: 'micromentor-b8317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCiUJ_n4TpQRqZWY1ig25SwJNLGjUGrZw',
    appId: '1:970375826463:ios:b3d689aa342a9999a8d92a',
    messagingSenderId: '970375826463',
    projectId: 'micromentor-b8317',
    storageBucket: 'micromentor-b8317.appspot.com',
    iosBundleId: 'org.micromentor.mmFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCiUJ_n4TpQRqZWY1ig25SwJNLGjUGrZw',
    appId: '1:970375826463:ios:a01a18259af92bf9a8d92a',
    messagingSenderId: '970375826463',
    projectId: 'micromentor-b8317',
    storageBucket: 'micromentor-b8317.appspot.com',
    iosBundleId: 'com.example.mmFlutterApp',
  );
}
