# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and deploy the IOS app to Firebase app distrubtion"
  lane :build_and_distribute_android_with_firebase do
    lastest_version = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_IOS_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    )

    updated_version = lastest_version[:buildVersion].to_i + 1

    sh("flutter", "build", "<CHANGE BUILD COMMAND>", "--build-number=#{updated_version}")
    firebase_app_distribution(
      app: ENV["FIREBASE_IOS_APP_ID"],
      groups: "testers",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      ipa_path: "<INSERT PATH HERE>"
    )
  end

end
