# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build and deploy the Android app to the Play Store"
  lane :build_and_deploy_android do
    sh("flutter", "build", "apk", "--release")

    upload_to_play_store(
      track: 'internal',  # or 'alpha', 'beta', 'production'
      json_key_data: ENV['PLAYSTORE_JSON_KEY'],  # Will explain how to set this up in GitHub Actions
      package_name: "org.micromentor.mm_flutter_app",
      apk: "./build/app/outputs/flutter-apk/app-release.apk"
    )
  end
end
