# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build and deploy the Android app to the Play Store"
  lane :build_and_deploy_android do
    version_code = google_play_track_version_codes(
      package_name: "org.micromentor.mm_flutter_app",
      track: "internal",
      json_key: "./fastlane/service_account.json",
      #json_key_data: ENV["PLAYSTORE_JSON_KEY"],  # Enable this for Github Actions
    )
     
    # Make sure to default to zero when there is no version in Playstore (ie, it`s a new app)
    version_code_play_store = version_code.fetch(0, 0).to_i
    update_version_code = version_code_play_store + 1

    sh("flutter", "build", "appbundle", "--build-number=#{update_version_code}")

    upload_to_play_store(
      track: "internal",  # or "alpha", "beta", "production"
      release_status: 'draft',
      json_key: "./fastlane/service_account.json",
      #json_key_data: ENV["PLAYSTORE_JSON_KEY"],  # Enable this for Github Actions
      package_name: "org.micromentor.mm_flutter_app",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
    )
  end

  desc "Build and deploy the Android app to Firebase app distrubtion"
  lane :build_and_distribute_android_with_firebase do
    sh("flutter", "build", "apk")
    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"],
      android_artifact_type: "APK",
      groups: "testers",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end

end
