name: Tests and formatters
on:
- pull_request
- push
jobs:
  dart-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.1'
    - name: See if formatting changes anything
      run: dart format --set-exit-if-changed .
  flutter-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.1'
    - name: Add assets/.env
      run: touch assets/.env
    - name: Fix subosito/flutter-action \#197
      run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.10.1-x64
    - name: See if tests are failing
      run: flutter test
