name: Release App with Fastlane (Firebase App Distribution)
on:
  push:
    branches:
      - 'app_distribution'
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.1'
    - uses: fwilhe2/setup-kotlin@main
      with:
        install-native: true
        version: 1.7.10
    - name: Add assets/.env
      run: touch assets/.env
    - name: Add Google Services JSON
      run: 'echo "$GOOGLE_SERVICES_JSON_FILE" > android/app/google-services.json'
      env:
        GOOGLE_SERVICES_JSON_FILE: ${{ secrets. GOOGLE_SERVICES_JSON_FILE }} 
    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - name: Install dependencies
      run: cd android && bundle install
    - name: Run app distribution
      run: cd android && bundle exec fastlane build_and_distribute_android_with_firebase
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
